name: Run_Tests

on: [pull_request, push]

jobs:
  build:
    name: Run All Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: MikeSchulze/gdUnit4-action@v1.1.1
        with:
          godot-version: '4.2.2'
          godot-net: true
          version: 'v4.2.5'
          paths: |
            res://tests/unit
          #project_dir: './TheMagicApprentice/'
          project_dir: './TheMagicApprentice/'
          publish-report: true
          timout: 5
          report-name: test_report
