# Runs all GDUnit4 tests
name: Run Tests

on: [pull_request]

jobs:
  build:
    name: Run All Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: MikeSchulze/gdUnit4-action@v1.1.1
        with:
          godot-version: '4.2.2'
          godot-net: true
          version: 'v4.2.5'
          paths: |
            res://tests/unit
            res://tests/integration
          #project_dir: './TheMagicApprentice/'
          project_dir: './TheMagicApprentice/'
          publish-report: true
          report-name: 'test_report'
          install-test-adapter: false
